server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticket_store_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ticket_user
    password: ticket_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret: a3NqaGdkamFza2hkamFzaGtkaGFza2poZGFza2pqYWRza2phc2hka2pha3NqaGRqYQ==

event:
  service-url: http://localhost:8082 # URL for the event service

payment:
  service-url: http://localhost:8084 # URL for the payment service

auth:
  service-url: http://localhost:8081 # URL for the auth service

logging: # Added logging configuration
  level:
    root: INFO