server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ticket_store_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ticket_user
    password: ticket_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: a3NqaGdkamFza2hkamFzaGtkaGFza2poZGFza2pqYWRza2phc2hka2pha3NqaGRqYQ==

event:
  service-url: http://event-service:8082 # URL for the event service

payment:
  service-url: http://payment-service:8084 # URL for the payment service

auth:
  service-url: http://auth-service:8081 # URL for the auth service

# Spring Mail settings for Docker environment (can be mocked or use a real SMTP)
  mail:
    host: mock-smtp.example.com # Placeholder for Docker
    port: 25
    username: user
    password: password
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
