server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ticket_store_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ticket_user
    password: ticket_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: a3NqaGdkamFza2hkamFzaGtkaGFza2poZGFza2pqYWRza2phc2hka2pha3NqaGRqYQ==

order:
  service-url: http://order-service:8083 # URL for the order service
