server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticket_store_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ticket_user
    password: ticket_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 'validate' trên môi trường production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: a3NqaGdkamFza2hkamFzaGtkaGFza2poZGFza2pqYWRza2phc2hka2pha3NqaGRqYQ==
  expiration: 3600000           # 1h = 3600000 ms
  refresh-expiration: 604800000 # 7 ngày

logging:
  level:
    root: INFO # Changed from INFO to DEBUG
    org.springframework.security: INFO
